stages:
  request:
    http: https://httpbin.org/ip

  hola:
    bash: echo -n hola

  generate_json:
    ruby: |-
      require 'json'

      def main
        {
          a: 1,
          b: "yeah"
        }
      end

  exit:
    dependencies:
      - hola
      - generate_json
      - request
    node: |-
      function main(msg, j, body) {
        ip = JSON.parse(body).origin;
        console.log("dew:", msg, j.b);
        console.log("My IP is: " + ip);
        return -1;
      }

# dummies:
#   a:

# watchers:
#   pepe:
#     watch: exit
#     pre:
#     post:
