stages:
  echo_bullshitter:
    bash: sleep 2 && echo hola

  b:
    ruby: |-
      require 'json'

      def main
        j = {
          a: 1,
          b: "yeah"
        }.to_json
        puts j
      end

  exit:
    dependencies:
      - echo_bullshitter
      - b
    node: |-
      function main() {
        console.log("dew");
      }

